<!DOCTYPE html>
<html>
<head>
    <title>Administration des articles - Mon premier blog !</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/admin.css">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
</head>
<body class="index-body">
<div class="container-fluid">
    <?php include ROOT . "App/View/commun/adminmenu.phtml" ?>

    <section class="col-9">
            <header class="pb-3">
                <!-- Si $article existe, on affiche "Modifier" SINON on affiche "Ajouter" -->
                <h4>Ajouter un article</h4>
            </header>
            <!-- Si $article existe, chaque champ du formulaire sera pré-remplit avec les informations de l'article -->
            <form action="update" method="post" enctype="multipart/form-data">
                <div class="form-group" style="display: none">
                    <label for="title">id :</label>
                    <input class="form-control" value="<?= $user->id ?>"  type="text"  name="user_id" id="id"/>
                </div>
                <div class="form-group">
                    <label for="title">Nom :</label>
                    <input class="form-control" value="<?= $user->firstname ?>"  type="text" name="firstname" id="firstname"/>
                </div>
                <div class="form-group">
                    <label for="summary">Prenom :</label>
                    <input class="form-control" value="<?= $user->lastname ?>" type="text"  name="lastname" id="lastname"/>
                </div>
                <div class="form-group">
                    <label for="content">Email :</label>
                    <input type="text" class="form-control" name="email" id="email" value="<?= $user->email ?>" />
                </div>

                <div class="form-group">
                    <label for="content">Mot de passe :</label>
                    <input type="text" class="form-control"  name="password" id="password"  value="<?= $user->password ?>"/>
                </div>

                <div class="form-group">
                    <label for="is_published">Admin ?</label>
                    <select class="form-control" name="is_admin">
                        id="is_admin">
                        <option value="0">Non</option>
                        <option value="1">Oui</option>
                    </select>
                </div>
                <div class="text-right">
                    <!-- Si $article existe, on affiche un lien de mise à jour -->
                    <input class="btn btn-success" type="submit" name="save" value="Enregistrer"/>
                </div>

            </form>

        </section>
    </div>
</div>
</body>
</html>
