<!DOCTYPE html>
<html>
<head>
    <title>Administration des utilisateurs - Mon premier blog !</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/admin.css">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
</head>
<body class="index-body">
<div class="container-fluid">
    <?php include ROOT . "App/View/commun/adminmenu.phtml" ?>

    <section class="col-9">
        <header class="pb-4 d-flex justify-content-between">
            <h4>Liste des utilisateurs</h4>
            <a class="btn btn-primary" href="addedit">Ajouter un utilisateur</a>
        </header>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Admin</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($users as $user){ ?>
                <tr>
                    <!-- htmlentities sert à écrire les balises html sans les interpréter -->
                    <th><?= $user->id ?></th>
                    <td><?= utf8_encode($user->firstname) ?></td>
                    <td><?= utf8_encode($user->lastname) ?></td>
                    <td><?= utf8_encode($user->email) ?></td>
                    <td><?= $user->is_admin ? "oui" : "non" ?></td>
                    <td>
                        <a href="addedit?user_id=<?= $user->id ?>" class="btn btn-warning">Modifier</a>
                        <a onclick="return confirm('Are you sure?')" href="delete?user_id=<?= $user->id ?>&action=delete" class="btn btn-danger">Supprimer</a>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </section>
</div>
</div>
</body>
</html>
