<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">
    <title>Document</title>
    <style>
        .btn {
            border: 1px solid rgba(0, 0, 255, .4);
            background: whitesmoke;
            padding: 5px 20px 5px 20px;
            box-shadow: none;
            border-radius: 8px;
            cursor: pointer;
            transition: all .3 cubic-bezier(0.175, 0.885, 0.32, 1.275)
        }

        .btn:focus {
            background: whitesmoke;
        }

        a {
            text-decoration: none;
            color: inherit;
        }

        .btn:hover {
            background: rgba(0, 0, 255, .4);
        }

        .validate {
            display: flex;
            justify-content: space-between;
            align-items: center;
            background-color: rgb(46, 69, 119);
            margin-bottom: 30px;
        }

        .info {
            flex: 0 0 70%;
            color: white;
        }

        .validate-ok {
            flex: 0 0 30%;
            text-align: center;
        }

        .payed {
            border: 1px solid lime;
            padding: 5px;
            color: lime;
        }

        .not-payed {
            border: 1px solid red;
            padding: 5px;
            color: red;
        }

        .lname {
            border: 1px solid rgb(46, 69, 119);
            color: rgb(46, 69, 119);
            padding: 5px;
        }

        .table-header {
            display: flex;
        }

        .table-th {
            flex: 0 0 calc(100%/6);
            color: white;
            background-color: rgb(46, 69, 119);
            text-align: center;
            font-weight: bold;
            line-height: 40px;
            height: 40px;
        }

        .table-line {
            display: flex;
        }

        .table-tr {
            flex: 0 0 calc(100%/6);
            text-align: center;
            line-height: 40px;
            height: 40px;
        }
    </style>
</head>

<body>
<div class="main">
    <?php include ROOT . "App/View/commun/header.phtml" ?>
    <section class="slider-hidden">
        <div style="max-width:100%">
            <img class="mySlide" src="../../public/images/img35.jpg" style="width:100%">
            <img class="mySlide" src="../../public/images/loisir.jpg" style="width:100%">
            <img class="mySlide" src="../../public/images/img34.jpg" style="width:100%">
        </div>
    </section>  
</div>
<?php include ROOT . "/App/View/commun/connection.phtml" ?>
<div class="validate">
    <div class="info">
        <p>Num de famille: 34r23</p>
        <p>Mr. DURAND</p>
        <p>Mme DURAND</p>
        <p>Enfants 5</p>
        <p>DURAND Jessyca</p>
    </div>
    <div class="validate-ok">
        <button class="btn">Valider</button>
    </div>
</div>
<div class="resume">
    <div class="table">
        <div class="table-header">
            <div class="table-th">Nom</div>
            <div class="table-th">N. facture</div>
            <div class="table-th">Date</div>
            <div class="table-th">Statut</div>
            <div class="table-th">Consulté</div>
            <div class="table-th">Téléchager</div>
        </div>
        <div class="table-body">
            <div class="table-line">
                <div class="table-tr"><span class="lname">Durant</span></div>
                <div class="table-tr">234234</div>
                <div class="table-tr">20/02/20</div>
                <div class="table-tr"><span class="payed">Payé</span></div>
                <div class="table-tr"><i class="fas fa-search-plus"></i></div>
                <div class="table-tr"><a href=""><i class="fas fa-download"></i></a></div>
            </div>
            <div class="table-line">
                <div class="table-tr"><span class="lname">Durant</span></div>
                <div class="table-tr">234234</div>
                <div class="table-tr">20/02/20</div>
                <div class="table-tr"><span class="not-payed">Impayé</span></div>
                <div class="table-tr"><i class="fas fa-search-plus"></i></div>
                <div class="table-tr"><a href=""><i class="fas fa-download"></i></a></div>
            </div>
        </div>
    </div>
</div>
</div>
<?php include ROOT . "/App/View/commun/footer.phtml" ?>

</body>

</html>