<!DOCTYPE html>
<html>
<head>
    <title>Administration des articles - Mon premier blog !</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/admin.css">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
</head>
<body class="index-body">
<div class="container-fluid">
    <?php include ROOT . "App/View/commun/adminmenu.phtml" ?>
    <section class="col-9">
            <header class="pb-3">
                <!-- Si $article existe, on affiche "Modifier" SINON on affiche "Ajouter" -->
                <h4>Ajouter un article</h4>
            </header>
            <!-- Si $article existe, chaque champ du formulaire sera pré-remplit avec les informations de l'article -->
            <form action="update" method="post" enctype="multipart/form-data">
                <div class="form-group" style="display: none">
                    <label for="title">Titre :</label>
                    <input class="form-control" type="text" value="<?php echo $article->id ?>"
                           name="id" id="id"/>
                </div>
                <div class="form-group">
                    <label for="title">Titre :</label>
                    <input class="form-control" type="text" value="<?php echo utf8_encode($article->title) ?>"
                           name="title" id="title"/>
                </div>
                <div class="form-group">
                    <label for="summary">Résumé :</label>
                    <input class="form-control" type="text" value="<?= $article->summary ?>" name="summary"
                           id="summary"/>
                </div>
                <div class="form-group">
                    <label for="content">Contenu :</label>
                    <textarea class="form-control" name="content" id="content"><?= $article->content ?></textarea>
                </div>

                <div class="form-group">
                    <label for="published_at">Date de publication :</label>
                    <input class="form-control" type="date" value="<?= $article->created_at ?>" name="created_at"
                           id="published_at"/>
                </div>

                <div class="form-group">
                    <label for="is_published">Publié ?</label>
                    <select class="form-control" name="is_published" value="<?= $article->is_published ?>"
                            id="is_published">
                        <option value="0">Non</option>
                        <option value="1">Oui</option>
                    </select>
                </div>


                <div class="text-right">
                    <!-- Si $article existe, on affiche un lien de mise à jour -->
                    <input class="btn btn-success" type="submit" name="save" value="Enregistrer"/>
                </div>

                <!-- Si $article existe, on ajoute un champ caché contenant l'id de l'article à modifier pour la requête UPDATE -->

            </form>

        </section>
    </div>
</div>
</body>
</html>
