<!DOCTYPE html>
<html>
<head>
    <title>Administration des articles - Mon premier blog !</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/admin.css">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
</head>
<body class="index-body">
<div class="container-fluid">
    <?php include ROOT . "App/View/commun/adminmenu.phtml" ?>

    <section class="col-9">
        <header class="pb-4 d-flex justify-content-between">
            <h4>Liste des articles</h4>
            <a class="btn btn-primary" href="addedit">Ajouter un article</a>
        </header>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Titre</th>
                <th>Date de création</th>
                <th>Image</th>
                <th>Publié</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($articles as $article){ ?>
            <tr>
                <!-- htmlentities sert à écrire les balises html sans les interpréter -->
                <th><?= $article->id ?></th>
                <td><?= utf8_encode($article->title) ?></td>
                <td><?= utf8_encode($article->created_at) ?></td>
                <td><?= utf8_encode($article->image) ?></td>
                <td>
                    <?= $article->is_published ?>								</td>
                <td>
                    <a href="addedit?article_id=<?= $article->id ?>" class="btn btn-warning">Modifier</a>
                    <a onclick="return confirm('Are you sure?')" href="delete?article_id=<?= $article->id ?>&action=delete" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
            <?php } ?>

            </tbody>
        </table>
    </section>
</div>
</div>
</body>
</html>