<!DOCTYPE html>
<html>
<head>
    <title>Administration des catégories - Mon premier blog !</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/admin.css">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
</head>
<body class="index-body">
<div class="container-fluid">
    <header class="row mb-3 main-header">
        <div class="col py-4 text-center">
            <a href="index.php"><b>Administration - Mon premier blog !</b></a>
        </div>
    </header>			<div class="row my-3 index-content">
    ﻿<nav class="col-3 py-2 categories-nav">
    <a class="d-block btn btn-warning mb-4 mt-2" href="../../index.php">Site</a>
    <ul>
        <li><a href="user_list.html">Gestion des utilisateurs (1)</a></li>
        <li><a href="">Gestion des catégories (4)</a></li>
        <li><a href="../View/adminarticle/article_list.phtml">Gestion des articles (9)</a></li>
    </ul>
</nav>
    <section class="col-9">
        <header class="pb-4 d-flex justify-content-between">
            <h4>Liste des catégories</h4>
            <a class="btn btn-primary" href="category-form.php">Ajouter une catégorie</a>
        </header>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <!-- htmlentities sert à écrire les balises html sans les interpréter -->
                <th>108</th>
                <td>Jeux vid&eacute;os</td>
                <td>Videos, tests...</td>
                <td>
                    <a href="category-form.php?category_id=108&action=edit" class="btn btn-warning">Modifier</a>
                    <a onclick="return confirm('Are you sure?')" href="category-list.php?category_id=108&action=delete" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
            <tr>
                <!-- htmlentities sert à écrire les balises html sans les interpréter -->
                <th>52</th>
                <td>Th&eacute;&acirc;tre</td>
                <td>Dates, repr&eacute;sentations, avis...</td>
                <td>
                    <a href="category-form.php?category_id=52&action=edit" class="btn btn-warning">Modifier</a>
                    <a onclick="return confirm('Are you sure?')" href="category-list.php?category_id=52&action=delete" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
            <tr>
                <!-- htmlentities sert à écrire les balises html sans les interpréter -->
                <th>47</th>
                <td>Musique</td>
                <td>Concerts, sorties d'albums, festivals...</td>
                <td>
                    <a href="category-form.php?category_id=47&action=edit" class="btn btn-warning">Modifier</a>
                    <a onclick="return confirm('Are you sure?')" href="category-list.php?category_id=47&action=delete" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
            <tr>
                <!-- htmlentities sert à écrire les balises html sans les interpréter -->
                <th>9</th>
                <td>Cin&eacute;ma</td>
                <td>Trailers, infos, sorties...</td>
                <td>
                    <a href="category-form.php?category_id=9&action=edit" class="btn btn-warning">Modifier</a>
                    <a onclick="return confirm('Are you sure?')" href="category-list.php?category_id=9&action=delete" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
            </tbody>
        </table>
    </section>
</div>
</div>
</body>
</html>