<!DOCTYPE html>
<html>
<head>
    <title>Administration des utilisateurs - Mon premier blog !</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/admin.css">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
</head>
<body class="index-body">
<div class="container-fluid">
    <header class="row mb-3 main-header">
        <div class="col py-4 text-center">
            <a href="index.php"><b>Administration - Mon premier blog !</b></a>
        </div>
    </header>			<div class="row my-3 index-content">
    ﻿<nav class="col-3 py-2 categories-nav">
    <a class="d-block btn btn-warning mb-4 mt-2" href="../../admin/index.html">Site</a>
    <ul>
        <li><a href="user_list.phtml">Gestion des utilisateurs (1)</a></li>
        <li><a href="">Gestion des catégories (4)</a></li>
        <li><a href="article_list.phtml">Gestion des articles (9)</a></li>
    </ul>
</nav>
    <section class="col-9">
        <header class="pb-4 d-flex justify-content-between">
            <h4>Liste des utilisateurs</h4>
            <a class="btn btn-primary" href="user_list.phtml">Ajouter un utilisateur</a>
        </header>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Admin</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <!-- htmlentities sert à écrire les balises html sans les interpréter -->
                <th>19</th>
                <td>YOUSSEF</td>
                <td>GRYS</td>
                <td>Elgrysyoussef78@gmail.com</td>
                <td>Oui</td>
                <td>
                    <a href="user-form.php?user_id=19&action=edit" class="btn btn-warning">Modifier</a>
                    <a onclick="return confirm('Are you sure?')" href="user-list.php?user_id=19&action=delete" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
            </tbody>
        </table>
    </section>
</div>
</div>
</body>
</html>
