<link rel="stylesheet" type="text/css" href="../../../public/css/style.css">

<div class="mask" onclick="hideModal()">
</div>

<div class="modal connection-modal mini">
    <div class="modal-title">
        Formulaire
    </div>
    <div class="modal-body">
        <form method="post" action="/Home/connect">
            <div class="form-connection-controller">
                <div class="label-controller">
                    <label for="">Email</label>
                </div>
                <div class="input-controller"><input name="email" type="email"></div>

            </div>
            <div class="form-connection-controller">
                <div class="label-controller"><label for="">Mot de passe</label></div>
                <div class="input-controller"><input name="pwd" type="password"></div>
            </div>
            <div class="form-submit-controller">
                <button type="submit">Connexion</button>
            </div>
            <div class="form-psw-forgot">
                Mot de passe oublié?
            </div>
    </div>

    </form>
</div>


<script>

    function hideModal() {
        document.querySelector(".modal").classList.remove("active")
        document.querySelector(".mask").classList.remove("active")
    }
</script>
