   <section class="steap-blue">
       <div class="info">

           <img src="../../public/images/logotrans.png">
           <h1>HÔTEL DE VILLE</h1>
           <p>1, place Saint-Blaise 78955 CARRIÈRES-SOUS-POISSY</p>
           <p>01 39 22 36 00 - </p>
       </div>
   </section>
   <section class="steap-black">
       <div class="footer">
           <div class="footerOne">
               <img src="../../public/images/logotrans.png">
               <div class="footerTwo">
                   <p><a href="#">Carriere Sous Poissy</a></p>
                   <p><a href="#">A Propos</a></p>
                   <p><a href="/Faq/index">FAQ</a></p>
               </div>
           </div>
           <div class="map-footer">
               <iframe
                   src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2620.5100634300106!2d2.0320219155582135!3d48.943772879295935!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e68be0351aaa49%3A0xac10ec3cc084be3!2sMairie+de+Carri%C3%A8res-sous-Poissy!5e0!3m2!1sfr!2sfr!4v1560864108316!5m2!1sfr!2sfr"
                   width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
           </div>
   </section>

   <style>
       @media only screen and (max-width: 1210px) {
           .footerOne {
               transform: translateY(0);
               width: 100vw;
           }

           iframe {
               width: 100vw;
           }

           .map-footer {
               position: relative;
           }

       }
   </style>