<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="../../public/css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,300i,400,400i" rel="stylesheet">
    <script src="../../public/js/main.js"></script>
    <title>Carriere Sous Poissy</title>
<body>
<div class="main">
    <?php include ROOT . "App/View/commun/header.phtml" ?>
    <section>
        <div style="max-width:100%">
            <img class="mySlide" src="../../public/images/img35.jpg" style="width:100%">
            <img class="mySlide" src="../../public/images/loisir.jpg" style="width:100%">
            <img class="mySlide" src="../../public/images/img34.jpg" style="width:100%">
        </div>
    </section>
    <section class="mainOne">
        <div class="row">
            <div>
                <img src="../../public/images/mairie.png">
            </div>
            <h5>Lovée dans une boucle de la Seine, Carrières-sous-Poissy offre à ses habitants tout le charme d'une
                petite
                ville moderne,<br>
                fière d'un passé toujours inscrit dans la diversité de ses paysages :<br> surprenantes carrières de
                calcaire, chemin verdoyant qui borde le Fleuve et le canal de la Dérivation,<br>
                hier haut lieu de la batellerie, étang aux eaux poissonneuses célèbre pour ses petites maisons de
                pêcheurs
                flottantes, vaste plaine maraîchère témoin d'une activité agricole autrefois prospère...<br>
                À quelques encablures de la capitale, comme un air de campagne !</h5>


            <li>Région : Île-de-France</li>
            <li>Département : Yvelines</li>
            <li>Sous-préfecture de Saint-Germain-en-Laye</li>
            <li>Arrondissement de Saint-Germain-en-Laye (528 320 habitants)</li>
            <li>12e Circonscription législative des Yvelines</li>
            <li>Canton de Poissy-Nord</li>
            <li>Code postal : 78955</li>
            <li>Superficie* : 7,2 Km2</li>
            <li>Densité* : 2134 hab/km2</
            </li>
            <li>Altitude : 32,80 m</li>
            <li>Population : 15 343 Carriérois (recensement INSEE* 2014).</li>
            <li>Situation : sur la rive droite de la Seine, à 30 minutes de Paris par le RER et le train (gare SNCF/RATP
                de Poissy) et en voiture via l'A13 et l'A14 (accès par Orgeval).
            </li>


        </div>
    </section>

    <?php include ROOT . "App/View/commun/footer.phtml" ?>
</div>
<?php include ROOT . "App/View/commun/connection.phtml" ?>

</body>
<script src="../../../public/js/slider.js"></script>
</html>