<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="../../public/css/style.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .accordion {
            background-color: #294d90;
            color: #444;
            /* cursor: pointer; */
            padding: 18px;
            width: 100%;
            border: none;
            /* text-align: left; */
            outline: none;
            font-size: 15px;
            transition: 0.4s;
            color: #ffffff;
        }

        .active, .accordion:hover {
            background-color: #3875cb;
        }

        .accordion:after {
            content: '\002B';
            color: #ffffff;
            font-weight: bold;
            float: right;
            margin-left: 5px;
        }

        .active:after {
            content: "\2212";
        }

        .panel {
            padding: 0 18px;
            background-color: white;
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.2s ease-out;
        }
    </style>
</head>
<body>
<div class="main">
    <?php include ROOT . "App/View/commun/header.phtml" ?>
    <section class="slider-hidden">
        <div style="max-width:100%">
            <img class="mySlide" src="../../public/images/img35.jpg" style="width:100%">
            <img class="mySlide" src="../../public/images/loisir.jpg" style="width:100%">
            <img class="mySlide" src="../../public/images/img34.jpg" style="width:100%">
        </div><?php include ROOT . "/App/View/commun/connection.phtml" ?>
    </section>
    <button class="accordion">Qui vote le budget de la commune ?</button>
    <div class="panel">
        <p>Le budget est établi sous la responsabilité du Maire par les services municipaux et voté par le Conseil
            Municipal.</p>
    </div>

    <button class="accordion">Quand vote-t-on le budget de la commune ?</button>
    <div class="panel">
        <p>Le budget primitif doit être adopté avant le 15 avril, ou le 30 avril les années d’élections municipales.
            Des décisions modificatives peuvent intervenir en cours d'année pour procéder à des ajustements de recettes
            ou de dépenses.
            Le compte administratif, qui présente le résultat de l'exercice budgétaire, doit être voté avant le 30
            juin.</p>
    </div>

    <button class="accordion">Puis-je assister au vote du budget ?</button>
    <div class="panel">
        <p>Toutes les séances du Conseil Municipal sont publiques et les citoyens peuvent y assister, notamment à la
            discussion et au vote du budget, mais ils n’ont pas le droit d’intervenir dans les débats..

            Pour vous renseigner sur les dates et les ordres du jour des séances du Conseil Municipal, consultez les
            tableaux d’affichage à la mairie.</p>
    </div>

    <button class="accordion">Puis-je assister au vote du budget ?</button>
    <div class="panel">
        <p>Toutes les séances du Conseil Municipal sont publiques et les citoyens peuvent y assister, notamment à la
            discussion et au vote du budget, mais ils n’ont pas le droit d’intervenir dans les débats..

            Pour vous renseigner sur les dates et les ordres du jour des séances du Conseil Municipal, consultez les
            tableaux d’affichage à la mairie.</p>
    </div>
    <button class="accordion">Puis-je assister au vote du budget ?</button>
    <div class="panel">
        <p>Toutes les séances du Conseil Municipal sont publiques et les citoyens peuvent y assister, notamment à la
            discussion et au vote du budget, mais ils n’ont pas le droit d’intervenir dans les débats..

            Pour vous renseigner sur les dates et les ordres du jour des séances du Conseil Municipal, consultez les
            tableaux d’affichage à la mairie.</p>
    </div>
</div>
<script>
    let acc = document.getElementsByClassName("accordion")
    let i

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            let panel = this.nextElementSibling
            if (panel.style.maxHeight) {
                panel.style.maxHeight = null
            } else {
                panel.style.maxHeight = panel.scrollHeight + "px"
            }
        })
    }
</script>

</body>
</html>